# Generated by Django 4.2.4 on 2023-10-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="csv_file",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]