# Generated by Django 4.0.3 on 2023-10-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_csvdata_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='csv_file',
            field=models.FileField(null=True, upload_to='PPI/'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='csv_info',
            field=models.FloatField(default=0.0),
        ),
    ]